//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class AC01 : XPLiteObject
	{
		string fAC001;
		[Key]
		[Size(20)]
		public string AC001
		{
			get { return fAC001; }
			set { SetPropertyValue<string>(nameof(AC001), ref fAC001, value); }
		}
		string fAC003;
		[Size(40)]
		public string AC003
		{
			get { return fAC003; }
			set { SetPropertyValue<string>(nameof(AC003), ref fAC003, value); }
		}
		string fAC002;
		[Size(3)]
		public string AC002
		{
			get { return fAC002; }
			set { SetPropertyValue<string>(nameof(AC002), ref fAC002, value); }
		}
		int fAC004;
		public int AC004
		{
			get { return fAC004; }
			set { SetPropertyValue<int>(nameof(AC004), ref fAC004, value); }
		}
		string fAC014;
		[Size(80)]
		public string AC014
		{
			get { return fAC014; }
			set { SetPropertyValue<string>(nameof(AC014), ref fAC014, value); }
		}
		string fAC005;
		[Size(80)]
		public string AC005
		{
			get { return fAC005; }
			set { SetPropertyValue<string>(nameof(AC005), ref fAC005, value); }
		}
		string fAC006;
		[Size(10)]
		public string AC006
		{
			get { return fAC006; }
			set { SetPropertyValue<string>(nameof(AC006), ref fAC006, value); }
		}
		string fAC007;
		[Size(10)]
		public string AC007
		{
			get { return fAC007; }
			set { SetPropertyValue<string>(nameof(AC007), ref fAC007, value); }
		}
		string fAC008;
		[Size(150)]
		public string AC008
		{
			get { return fAC008; }
			set { SetPropertyValue<string>(nameof(AC008), ref fAC008, value); }
		}
		DateTime fAC010;
		public DateTime AC010
		{
			get { return fAC010; }
			set { SetPropertyValue<DateTime>(nameof(AC010), ref fAC010, value); }
		}
		string fAC009;
		[Size(200)]
		public string AC009
		{
			get { return fAC009; }
			set { SetPropertyValue<string>(nameof(AC009), ref fAC009, value); }
		}
		DateTime fAC020;
		public DateTime AC020
		{
			get { return fAC020; }
			set { SetPropertyValue<DateTime>(nameof(AC020), ref fAC020, value); }
		}
		DateTime? fAC015;
		[Indexed(Name = @"IDX_AC01")]
		public DateTime? AC015
		{
			get { return fAC015; }
			set { SetPropertyValue<DateTime?>(nameof(AC015), ref fAC015, value); }
		}
		DateTime? fAC018;
		public DateTime? AC018
		{
			get { return fAC018; }
			set { SetPropertyValue<DateTime?>(nameof(AC018), ref fAC018, value); }
		}
		string fAC050;
		[Size(50)]
		public string AC050
		{
			get { return fAC050; }
			set { SetPropertyValue<string>(nameof(AC050), ref fAC050, value); }
		}
		string fAC051;
		[Size(50)]
		public string AC051
		{
			get { return fAC051; }
			set { SetPropertyValue<string>(nameof(AC051), ref fAC051, value); }
		}
		string fAC052;
		[Size(50)]
		public string AC052
		{
			get { return fAC052; }
			set { SetPropertyValue<string>(nameof(AC052), ref fAC052, value); }
		}
		string fAC055;
		[Size(200)]
		public string AC055
		{
			get { return fAC055; }
			set { SetPropertyValue<string>(nameof(AC055), ref fAC055, value); }
		}
		string fAC060;
		[Size(20)]
		public string AC060
		{
			get { return fAC060; }
			set { SetPropertyValue<string>(nameof(AC060), ref fAC060, value); }
		}
		string fAC100;
		[Size(10)]
		public string AC100
		{
			get { return fAC100; }
			set { SetPropertyValue<string>(nameof(AC100), ref fAC100, value); }
		}
		DateTime fAC200;
		public DateTime AC200
		{
			get { return fAC200; }
			set { SetPropertyValue<DateTime>(nameof(AC200), ref fAC200, value); }
		}
		string fAC110;
		[Size(10)]
		public string AC110
		{
			get { return fAC110; }
			set { SetPropertyValue<string>(nameof(AC110), ref fAC110, value); }
		}
		DateTime fAC220;
		public DateTime AC220
		{
			get { return fAC220; }
			set { SetPropertyValue<DateTime>(nameof(AC220), ref fAC220, value); }
		}
		string fAC099;
		[Size(200)]
		public string AC099
		{
			get { return fAC099; }
			set { SetPropertyValue<string>(nameof(AC099), ref fAC099, value); }
		}
		string fSTATUS;
		[Size(3)]
		public string STATUS
		{
			get { return fSTATUS; }
			set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
		}
	}

}
