//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class BO01 : XPLiteObject
	{
		string fBO001;
		[Key]
		[Size(50)]
		public string BO001
		{
			get { return fBO001; }
			set { SetPropertyValue<string>(nameof(BO001), ref fBO001, value); }
		}
		string fBO003;
		[Size(50)]
		public string BO003
		{
			get { return fBO003; }
			set { SetPropertyValue<string>(nameof(BO003), ref fBO003, value); }
		}
		char fBO004;
		public char BO004
		{
			get { return fBO004; }
			set { SetPropertyValue<char>(nameof(BO004), ref fBO004, value); }
		}
	}

}
