//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class CB01 : XPLiteObject
	{
		string fCB001;
		[Key]
		[Size(10)]
		public string CB001
		{
			get { return fCB001; }
			set { SetPropertyValue<string>(nameof(CB001), ref fCB001, value); }
		}
		string fCB002;
		[Size(3)]
		public string CB002
		{
			get { return fCB002; }
			set { SetPropertyValue<string>(nameof(CB002), ref fCB002, value); }
		}
		string fCB003;
		public string CB003
		{
			get { return fCB003; }
			set { SetPropertyValue<string>(nameof(CB003), ref fCB003, value); }
		}
		string fCB005;
		[Size(10)]
		public string CB005
		{
			get { return fCB005; }
			set { SetPropertyValue<string>(nameof(CB005), ref fCB005, value); }
		}
		string fSTATUS;
		[Size(3)]
		public string STATUS
		{
			get { return fSTATUS; }
			set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
		}
		string fCB006;
		[Size(500)]
		public string CB006
		{
			get { return fCB006; }
			set { SetPropertyValue<string>(nameof(CB006), ref fCB006, value); }
		}
	}

}
