//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class FA01 : XPLiteObject
	{
		string fFA001;
		[Key]
		[Size(10)]
		public string FA001
		{
			get { return fFA001; }
			set { SetPropertyValue<string>(nameof(FA001), ref fFA001, value); }
		}
		string fFA002;
		[Size(3)]
		public string FA002
		{
			get { return fFA002; }
			set { SetPropertyValue<string>(nameof(FA002), ref fFA002, value); }
		}
		string fAC001;
		[Size(10)]
		public string AC001
		{
			get { return fAC001; }
			set { SetPropertyValue<string>(nameof(AC001), ref fAC001, value); }
		}
		string fFA003;
		[Indexed(Name = @"IDX_FA01_FA003")]
		public string FA003
		{
			get { return fFA003; }
			set { SetPropertyValue<string>(nameof(FA003), ref fFA003, value); }
		}
		decimal fFA004;
		public decimal FA004
		{
			get { return fFA004; }
			set { SetPropertyValue<decimal>(nameof(FA004), ref fFA004, value); }
		}
		string fFA180;
		[Size(200)]
		public string FA180
		{
			get { return fFA180; }
			set { SetPropertyValue<string>(nameof(FA180), ref fFA180, value); }
		}
		string fFA100;
		[Indexed(Name = @"IDX_FA01_FA100")]
		[Size(10)]
		public string FA100
		{
			get { return fFA100; }
			set { SetPropertyValue<string>(nameof(FA100), ref fFA100, value); }
		}
		DateTime fFA200;
		public DateTime FA200
		{
			get { return fFA200; }
			set { SetPropertyValue<DateTime>(nameof(FA200), ref fFA200, value); }
		}
		string fSTATUS;
		[Indexed(Name = @"IDX_FA01_STATUS")]
		[Size(3)]
		public string STATUS
		{
			get { return fSTATUS; }
			set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
		}
		string fWS001;
		[Size(10)]
		public string WS001
		{
			get { return fWS001; }
			set { SetPropertyValue<string>(nameof(WS001), ref fWS001, value); }
		}
		string fFA099;
		[Size(20)]
		public string FA099
		{
			get { return fFA099; }
			set { SetPropertyValue<string>(nameof(FA099), ref fFA099, value); }
		}
	}

}
