//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class LY01 : XPLiteObject
	{
		string fLY001;
		[Key]
		[Size(10)]
		public string LY001
		{
			get { return fLY001; }
			set { SetPropertyValue<string>(nameof(LY001), ref fLY001, value); }
		}
		string fRG001;
		[Size(10)]
		public string RG001
		{
			get { return fRG001; }
			set { SetPropertyValue<string>(nameof(RG001), ref fRG001, value); }
		}
		int fLY002;
		public int LY002
		{
			get { return fLY002; }
			set { SetPropertyValue<int>(nameof(LY002), ref fLY002, value); }
		}
		decimal fPRICE;
		public decimal PRICE
		{
			get { return fPRICE; }
			set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
		}
	}

}
