//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class RC01 : XPLiteObject
	{
		string fRC001;
		[Key]
		[Size(10)]
		public string RC001
		{
			get { return fRC001; }
			set { SetPropertyValue<string>(nameof(RC001), ref fRC001, value); }
		}
		string fRC002;
		[Size(3)]
		public string RC002
		{
			get { return fRC002; }
			set { SetPropertyValue<string>(nameof(RC002), ref fRC002, value); }
		}
		string fRC202;
		[Size(3)]
		public string RC202
		{
			get { return fRC202; }
			set { SetPropertyValue<string>(nameof(RC202), ref fRC202, value); }
		}
		string fRC003;
		[Indexed(Name = @"IDX_RC01_RC003")]
		[Size(40)]
		public string RC003
		{
			get { return fRC003; }
			set { SetPropertyValue<string>(nameof(RC003), ref fRC003, value); }
		}
		string fRC303;
		[Size(40)]
		public string RC303
		{
			get { return fRC303; }
			set { SetPropertyValue<string>(nameof(RC303), ref fRC303, value); }
		}
		int fRC004;
		public int RC004
		{
			get { return fRC004; }
			set { SetPropertyValue<int>(nameof(RC004), ref fRC004, value); }
		}
		int? fRC404;
		public int? RC404
		{
			get { return fRC404; }
			set { SetPropertyValue<int?>(nameof(RC404), ref fRC404, value); }
		}
		string fRC014;
		[Size(80)]
		public string RC014
		{
			get { return fRC014; }
			set { SetPropertyValue<string>(nameof(RC014), ref fRC014, value); }
		}
		string fRC050;
		[Size(50)]
		public string RC050
		{
			get { return fRC050; }
			set { SetPropertyValue<string>(nameof(RC050), ref fRC050, value); }
		}
		string fRC051;
		[Size(50)]
		public string RC051
		{
			get { return fRC051; }
			set { SetPropertyValue<string>(nameof(RC051), ref fRC051, value); }
		}
		string fRC052;
		[Size(50)]
		public string RC052
		{
			get { return fRC052; }
			set { SetPropertyValue<string>(nameof(RC052), ref fRC052, value); }
		}
		string fRC055;
		[Size(200)]
		public string RC055
		{
			get { return fRC055; }
			set { SetPropertyValue<string>(nameof(RC055), ref fRC055, value); }
		}
		string fRC099;
		[Size(200)]
		public string RC099
		{
			get { return fRC099; }
			set { SetPropertyValue<string>(nameof(RC099), ref fRC099, value); }
		}
		string fRC109;
		[Indexed(Name = @"IDX_RC01_RC109")]
		[Size(50)]
		public string RC109
		{
			get { return fRC109; }
			set { SetPropertyValue<string>(nameof(RC109), ref fRC109, value); }
		}
		string fRC110;
		[Size(10)]
		public string RC110
		{
			get { return fRC110; }
			set { SetPropertyValue<string>(nameof(RC110), ref fRC110, value); }
		}
		string fRC120;
		[Size(10)]
		public string RC120
		{
			get { return fRC120; }
			set { SetPropertyValue<string>(nameof(RC120), ref fRC120, value); }
		}
		string fRC130;
		[Size(10)]
		public string RC130
		{
			get { return fRC130; }
			set { SetPropertyValue<string>(nameof(RC130), ref fRC130, value); }
		}
		DateTime fRC140;
		public DateTime RC140
		{
			get { return fRC140; }
			set { SetPropertyValue<DateTime>(nameof(RC140), ref fRC140, value); }
		}
		DateTime fRC150;
		public DateTime RC150
		{
			get { return fRC150; }
			set { SetPropertyValue<DateTime>(nameof(RC150), ref fRC150, value); }
		}
		string fSOURCE;
		[Size(3)]
		public string SOURCE
		{
			get { return fSOURCE; }
			set { SetPropertyValue<string>(nameof(SOURCE), ref fSOURCE, value); }
		}
		string fSTATUS;
		[Size(3)]
		public string STATUS
		{
			get { return fSTATUS; }
			set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
		}
		string fRC100;
		[Size(10)]
		public string RC100
		{
			get { return fRC100; }
			set { SetPropertyValue<string>(nameof(RC100), ref fRC100, value); }
		}
		DateTime fRC200;
		public DateTime RC200
		{
			get { return fRC200; }
			set { SetPropertyValue<DateTime>(nameof(RC200), ref fRC200, value); }
		}
	}

}
