//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class RC04 : XPLiteObject
	{
		string fRC001;
		[Indexed(Name = @"IDX_RC04_RC001")]
		[Size(10)]
		public string RC001
		{
			get { return fRC001; }
			set { SetPropertyValue<string>(nameof(RC001), ref fRC001, value); }
		}
		string fRC010;
		[Key]
		[Size(10)]
		public string RC010
		{
			get { return fRC010; }
			set { SetPropertyValue<string>(nameof(RC010), ref fRC010, value); }
		}
		DateTime fRC020;
		public DateTime RC020
		{
			get { return fRC020; }
			set { SetPropertyValue<DateTime>(nameof(RC020), ref fRC020, value); }
		}
		DateTime fRC022;
		public DateTime RC022
		{
			get { return fRC022; }
			set { SetPropertyValue<DateTime>(nameof(RC022), ref fRC022, value); }
		}
		decimal fPRICE;
		public decimal PRICE
		{
			get { return fPRICE; }
			set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
		}
		int fNUMS;
		public int NUMS
		{
			get { return fNUMS; }
			set { SetPropertyValue<int>(nameof(NUMS), ref fNUMS, value); }
		}
		decimal fRC030;
		public decimal RC030
		{
			get { return fRC030; }
			set { SetPropertyValue<decimal>(nameof(RC030), ref fRC030, value); }
		}
		string fRC031;
		[Size(3)]
		public string RC031
		{
			get { return fRC031; }
			set { SetPropertyValue<string>(nameof(RC031), ref fRC031, value); }
		}
		string fRC100;
		[Size(10)]
		public string RC100
		{
			get { return fRC100; }
			set { SetPropertyValue<string>(nameof(RC100), ref fRC100, value); }
		}
		DateTime fRC200;
		public DateTime RC200
		{
			get { return fRC200; }
			set { SetPropertyValue<DateTime>(nameof(RC200), ref fRC200, value); }
		}
		string fSTATUS;
		[Size(3)]
		public string STATUS
		{
			get { return fSTATUS; }
			set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
		}
	}

}
