//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class RG01 : XPLiteObject
	{
		string fRG001;
		[Key]
		[Size(10)]
		public string RG001
		{
			get { return fRG001; }
			set { SetPropertyValue<string>(nameof(RG001), ref fRG001, value); }
		}
		string fRG002;
		[Size(3)]
		public string RG002
		{
			get { return fRG002; }
			set { SetPropertyValue<string>(nameof(RG002), ref fRG002, value); }
		}
		string fRG003;
		[Size(50)]
		public string RG003
		{
			get { return fRG003; }
			set { SetPropertyValue<string>(nameof(RG003), ref fRG003, value); }
		}
		string fRG009;
		[Size(10)]
		public string RG009
		{
			get { return fRG009; }
			set { SetPropertyValue<string>(nameof(RG009), ref fRG009, value); }
		}
		int fRG010;
		public int RG010
		{
			get { return fRG010; }
			set { SetPropertyValue<int>(nameof(RG010), ref fRG010, value); }
		}
		int fRG011;
		public int RG011
		{
			get { return fRG011; }
			set { SetPropertyValue<int>(nameof(RG011), ref fRG011, value); }
		}
		int fRG020;
		public int RG020
		{
			get { return fRG020; }
			set { SetPropertyValue<int>(nameof(RG020), ref fRG020, value); }
		}
		int fRG021;
		public int RG021
		{
			get { return fRG021; }
			set { SetPropertyValue<int>(nameof(RG021), ref fRG021, value); }
		}
		string fRG030;
		[Size(3)]
		public string RG030
		{
			get { return fRG030; }
			set { SetPropertyValue<string>(nameof(RG030), ref fRG030, value); }
		}
		string fRG031;
		[Size(3)]
		public string RG031
		{
			get { return fRG031; }
			set { SetPropertyValue<string>(nameof(RG031), ref fRG031, value); }
		}
		string fRG033;
		[Size(3)]
		public string RG033
		{
			get { return fRG033; }
			set { SetPropertyValue<string>(nameof(RG033), ref fRG033, value); }
		}
		string fSTATUS;
		[Size(3)]
		public string STATUS
		{
			get { return fSTATUS; }
			set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
		}
	}

}
