//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class SA01_LOG : XPLiteObject
	{
		int fLOGID;
		[Key]
		public int LOGID
		{
			get { return fLOGID; }
			set { SetPropertyValue<int>(nameof(LOGID), ref fLOGID, value); }
		}
		string fSA001;
		[Size(10)]
		public string SA001
		{
			get { return fSA001; }
			set { SetPropertyValue<string>(nameof(SA001), ref fSA001, value); }
		}
		int fPRICE_OLD;
		public int PRICE_OLD
		{
			get { return fPRICE_OLD; }
			set { SetPropertyValue<int>(nameof(PRICE_OLD), ref fPRICE_OLD, value); }
		}
		int fNUMS_OLD;
		public int NUMS_OLD
		{
			get { return fNUMS_OLD; }
			set { SetPropertyValue<int>(nameof(NUMS_OLD), ref fNUMS_OLD, value); }
		}
		int fPRICE_NEW;
		public int PRICE_NEW
		{
			get { return fPRICE_NEW; }
			set { SetPropertyValue<int>(nameof(PRICE_NEW), ref fPRICE_NEW, value); }
		}
		int fNUMS_NEW;
		public int NUMS_NEW
		{
			get { return fNUMS_NEW; }
			set { SetPropertyValue<int>(nameof(NUMS_NEW), ref fNUMS_NEW, value); }
		}
		string fSA100;
		[Size(10)]
		public string SA100
		{
			get { return fSA100; }
			set { SetPropertyValue<string>(nameof(SA100), ref fSA100, value); }
		}
		DateTime fSA200;
		public DateTime SA200
		{
			get { return fSA200; }
			set { SetPropertyValue<DateTime>(nameof(SA200), ref fSA200, value); }
		}
	}

}
