//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class SI01 : XPLiteObject
	{
		string fSI001;
		[Key]
		[Size(10)]
		public string SI001
		{
			get { return fSI001; }
			set { SetPropertyValue<string>(nameof(SI001), ref fSI001, value); }
		}
		string fSI002;
		[Size(3)]
		public string SI002
		{
			get { return fSI002; }
			set { SetPropertyValue<string>(nameof(SI002), ref fSI002, value); }
		}
		string fSI003;
		public string SI003
		{
			get { return fSI003; }
			set { SetPropertyValue<string>(nameof(SI003), ref fSI003, value); }
		}
		decimal fPRICE;
		public decimal PRICE
		{
			get { return fPRICE; }
			set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
		}
		int fSORTID;
		public int SORTID
		{
			get { return fSORTID; }
			set { SetPropertyValue<int>(nameof(SORTID), ref fSORTID, value); }
		}
		string fSI077;
		[Size(3)]
		public string SI077
		{
			get { return fSI077; }
			set { SetPropertyValue<string>(nameof(SI077), ref fSI077, value); }
		}
		string fSI088;
		[Size(20)]
		public string SI088
		{
			get { return fSI088; }
			set { SetPropertyValue<string>(nameof(SI088), ref fSI088, value); }
		}
		string fSI099;
		[Size(10)]
		public string SI099
		{
			get { return fSI099; }
			set { SetPropertyValue<string>(nameof(SI099), ref fSI099, value); }
		}
		string fSTATUS;
		[Size(3)]
		public string STATUS
		{
			get { return fSTATUS; }
			set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
		}
	}

}
