//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class UR_MAPPER : XPLiteObject
	{
		string fUC001;
		[Indexed(@"RO001", Name = @"IDX_UR_MAPPER_1", Unique = true)]
		[Size(10)]
		public string UC001
		{
			get { return fUC001; }
			set { SetPropertyValue<string>(nameof(UC001), ref fUC001, value); }
		}
		string fRO001;
		[Size(10)]
		public string RO001
		{
			get { return fRO001; }
			set { SetPropertyValue<string>(nameof(RO001), ref fRO001, value); }
		}
		string fUM001;
		[Key]
		[Size(10)]
		public string UM001
		{
			get { return fUM001; }
			set { SetPropertyValue<string>(nameof(UM001), ref fUM001, value); }
		}
	}

}
