//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	[OptimisticLocking(false)]
	[DeferredDeletion(false)]
	public partial class V_ALLVALIDITEM : XPLiteObject
	{
		string fITEM_ID;
		[Key]
		public string ITEM_ID
		{
			get { return fITEM_ID; }
			set { SetPropertyValue<string>(nameof(ITEM_ID), ref fITEM_ID, value); }
		}
		string fITEM_TYPE;
		public string ITEM_TYPE
		{
			get { return fITEM_TYPE; }
			set { SetPropertyValue<string>(nameof(ITEM_TYPE), ref fITEM_TYPE, value); }
		}
		string fITEM_TYPE_TEXT;
		public string ITEM_TYPE_TEXT
		{
			get { return fITEM_TYPE_TEXT; }
			set { SetPropertyValue<string>(nameof(ITEM_TYPE_TEXT), ref fITEM_TYPE_TEXT, value); }
		}
		string fITEM_TEXT;
		public string ITEM_TEXT
		{
			get { return fITEM_TEXT; }
			set { SetPropertyValue<string>(nameof(ITEM_TEXT), ref fITEM_TEXT, value); }
		}
		string fPRICE;
		public string PRICE
		{
			get { return fPRICE; }
			set { SetPropertyValue<string>(nameof(PRICE), ref fPRICE, value); }
		}
		string fSORTID;
		public string SORTID
		{
			get { return fSORTID; }
			set { SetPropertyValue<string>(nameof(SORTID), ref fSORTID, value); }
		}
		string fZJF;
		public string ZJF
		{
			get { return fZJF; }
			set { SetPropertyValue<string>(nameof(ZJF), ref fZJF, value); }
		}
		string fINVTYPE;
		public string INVTYPE
		{
			get { return fINVTYPE; }
			set { SetPropertyValue<string>(nameof(INVTYPE), ref fINVTYPE, value); }
		}
		string fINVCODE;
		public string INVCODE
		{
			get { return fINVCODE; }
			set { SetPropertyValue<string>(nameof(INVCODE), ref fINVCODE, value); }
		}
	}

}
