//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class V_BINDINGSERVICE : XPLiteObject
	{
		string fSERVICEID;
		[Key]
		public string SERVICEID
		{
			get { return fSERVICEID; }
			set { SetPropertyValue<string>(nameof(SERVICEID), ref fSERVICEID, value); }
		}
		string fSERVICENAME;
		public string SERVICENAME
		{
			get { return fSERVICENAME; }
			set { SetPropertyValue<string>(nameof(SERVICENAME), ref fSERVICENAME, value); }
		}
	}

}
