//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Lime.Xpo.orcl
{

	public partial class V_UC01 : XPLiteObject
	{
		string fUC001;
		[Key]
		public string UC001
		{
			get { return fUC001; }
			set { SetPropertyValue<string>(nameof(UC001), ref fUC001, value); }
		}
		string fUC002;
		public string UC002
		{
			get { return fUC002; }
			set { SetPropertyValue<string>(nameof(UC002), ref fUC002, value); }
		}
		string fUC003;
		public string UC003
		{
			get { return fUC003; }
			set { SetPropertyValue<string>(nameof(UC003), ref fUC003, value); }
		}
		string fUC004;
		public string UC004
		{
			get { return fUC004; }
			set { SetPropertyValue<string>(nameof(UC004), ref fUC004, value); }
		}
		string fSTATUS;
		public string STATUS
		{
			get { return fSTATUS; }
			set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
		}
		[Persistent(@"ROLESLIST")]
		string fROLESLIST;
		[PersistentAlias("fROLESLIST")]
		public string ROLESLIST
		{
			get { return fROLESLIST; }
		}
	}

}
